[build]
  functions = "api"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"